
import React from 'react';
import Modal from '@/components/ui/Modal';
import Button from '@/components/ui/Button';

interface SubmissionModalProps {
  onClose: () => void;
  onDownloadSvg: () => void;
}

const SubmissionModal: React.FC<SubmissionModalProps> = ({ onClose, onDownloadSvg }) => {
  const repoUrl = 'https://github.com/new?template_name=vibe-coding-hackathon&template_owner=google-cloud-run-hackathon';
  const promptLink = 'https://gist.github.com/your-username/your-gist-id'; // Placeholder

  return (
    <Modal title="Hackathon Submission Helper" onClose={onClose}>
      <div className="space-y-6 text-gray-300">
        <p className="text-gray-400">Use these tools to help prepare your submission for the Cloud Run Hackathon.</p>
        
        <div>
          <h3 className="font-semibold text-lg text-cyan-400 mb-2">Phase 1: AI Studio</h3>
          <p className="text-sm text-gray-400 mb-3">This app was generated by AI Studio. Use the link below in your submission to share the prompts you used.</p>
          <label className="block text-sm font-medium text-gray-400 mb-1">Shareable Prompts Link (Placeholder)</label>
          <input
            type="text"
            readOnly
            value={promptLink}
            className="w-full bg-gray-800 border border-gray-600 rounded-md px-3 py-2 text-gray-400 cursor-copy"
            onFocus={(e) => e.target.select()}
          />
        </div>

        <div>
          <h3 className="font-semibold text-lg text-cyan-400 mb-2">Phase 2: AI Agents</h3>
          <p className="text-sm text-gray-400 mb-3">Generate an architecture diagram and create a public repository for your agent workflow code.</p>
          <div className="flex flex-col sm:flex-row gap-4">
            <Button onClick={onDownloadSvg} className="flex-1">
              Download Architecture.svg
            </Button>
            <a href={repoUrl} target="_blank" rel="noopener noreferrer" className="flex-1">
              <Button className="w-full">Create GitHub Repo</Button>
            </a>
          </div>
        </div>
      </div>
      <div className="mt-8 flex justify-end">
        <Button onClick={onClose} variant="secondary">Close</Button>
      </div>
    </Modal>
  );
};

export default SubmissionModal;
