export const GAME_IDEAS: string[] = [
  "A cat that uses portals to steal fish.",
  "A ghost trying to politely haunt a house without scaring anyone.",
  "A bee delivering pollen to flowers against the wind.",
  "A squirrel burying nuts for winter while dodging dogs.",
  "A slime that changes color to solve platforming puzzles.",
  "A robot chef that has to catch falling ingredients.",
  "A chameleon that uses camouflage to sneak past predators.",
  "A knight who fights with a magical, bouncy sword.",
  "A firefly lighting up a dark forest to find its friends.",
  "A penguin sliding down an icy hill to collect coins.",
  "A wizard who can only cast spells that create food.",
  "A sentient cloud that must rain on thirsty plants.",
  "A space janitor cleaning up asteroids with a giant vacuum.",
  "A dog on a skateboard delivering newspapers.",
  "A tiny mouse building a castle out of cheese.",
  "An octopus trying to juggle 8 different tasks at once.",
  "A gardener planting seeds that grow into musical instruments.",
  "A detective who is also a rubber duck, solving bathtub mysteries.",
  "A time-traveling hamster fixing paradoxes.",
  "A sentient coffee cup trying to avoid being drunk.",
  "A spider weaving trampolines to catch flies.",
  "A mole digging for treasure while avoiding underground pipes.",
  "A single-celled organism evolving to survive in a petri dish.",
  "A paper airplane navigating an office obstacle course.",
  "A turtle with a rocket shell racing against a hare.",
  "A snowman trying to get to the north pole before it melts.",
  "A sentient book collecting lost pages of its story.",
  "A bat using echolocation to navigate a musical cave.",
  "A chef flipping pancakes onto a series of moving plates.",
  "A sentient bowling ball trying to avoid the pins.",
  "A fire elemental that has to light beacons in a frozen land.",
  "A water droplet's journey from a cloud to the ocean.",
  "A cat herding yarn balls into a basket.",
  "A magical librarian organizing flying books.",
  "A robot that plants trees on a barren planet.",
  "A snail who has discovered the power of super-speed.",
  "A sentient paintbrush creating a living mural.",
  "A knight who is afraid of the dark.",
  "A puzzle game where you control gravity.",
  "A game where you play as a mischievous goose.",
  "A rhythm game about a blacksmith forging swords.",
  "A stealth game where you are a cookie trying to escape a kitchen.",
  "A puzzle game where you bend light to hit targets.",
  "A game about a lost star finding its way back to a constellation.",
  "A platformer where your shadow has a mind of its own.",
  "A game where you build a tower to the moon.",
  "A simulation of running a potion shop for adventurers.",
  "A game about a friendly monster who gives out hugs.",
  "A puzzle game where you rewind time to fix mistakes.",
  "A game about a bird learning to fly."
];
